### ISSUE TITLE
The environment fails to start with TyperError

### ISSUE THREAD

**Issue by peartobear** [ExchangeUnion/xud-docker#153]
```
root@ubuntu-s-2vcpu-4gb-blr1-01:~/xud-docker# ./xud.sh
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
A new version is available. Would you like to upgrade (Warning: this will restart your environment and cancel all open orders)? Y/n?N
Launching testnet environment...
/usr/bin/python
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../pull.py", line 199, in update
    result = get_pull_image(branch, image)
  File "../pull.py", line 165, in get_pull_image
    t1 = get_image_created_timestamp(m1)
  File "../pull.py", line 129, in get_image_created_timestamp
    return metadata["Labels"]["com.exchangeunion.image.created"]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by peartobear** [comment]
FIxed after pulling latest master
