### ISSUE TITLE
Aborting lndbtc logs throws error

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#197]
```
lndbtc_1     | 2019-10-04 02:00:47.482 [DBG] RPCS: [channelbalance] balance=0 BTC pending-open=0 BTC
lndbtc_1     | 2019-10-04 02:00:50.483 [DBG] RPCS: [channelbalance] balance=0 BTC pending-open=0 BTC
^CERROR: Aborting.
Traceback (most recent call last):
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 655, in logs
  File "compose/cli/log_printer.py", line 87, in run
  File "compose/cli/log_printer.py", line 247, in consume_queue
  File "queue.py", line 173, in get
  File "threading.py", line 299, in wait
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 73, in main
  File "logging/__init__.py", line 1337, in error
  File "logging/__init__.py", line 1444, in _log
  File "logging/__init__.py", line 1454, in handle
  File "logging/__init__.py", line 1516, in callHandlers
  File "logging/__init__.py", line 865, in handle
  File "logging/__init__.py", line 997, in emit
KeyboardInterrupt
[9360] Failed to execute script docker-compose
^C
mainnet >
```

**Comment by kilrau** [comment]
Not relevant anymore.
