### ISSUE TITLE
Util container exits when using logs

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#273]
Sometimes utils container exits when requesting logs. Will include a full log next time it happens.

```
2020-01-16 16:33:27.771 ERROR 1 --- [InputHandler] launcher.shell.InputHandler: Failed to execute command: 'logs xud'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/launcher/shell/shell.py", line 281, in _handle_command
    self.command_handler(cmd)  # sync
  File "/usr/local/lib/python3.8/site-packages/launcher/launcher.py", line 314, in handle_command
    self._cmd_logs.execute(args)
  File "/usr/local/lib/python3.8/site-packages/launcher/launcher.py", line 58, in execute
    self._shell.println(line)
  File "/usr/local/lib/python3.8/site-packages/launcher/shell/shell.py", line 471, in println
    print(line)
BlockingIOError: [Errno 11] write could not complete without blocking
2020-01-16 16:33:27.772 DEBUG 1 --- [InputHandler] launcher.shell.History: Committing command: <Command value=logs xud index=8 uncommitted=>
2020-01-16 16:33:27.772 ERROR 1 --- [InputHandler] launcher.shell.InputHandler: The loop exits unexpectedly
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/launcher/shell/shell.py", line 369, in run
    if not self._handle_input(ch):
  File "/usr/local/lib/python3.8/site-packages/launcher/shell/shell.py", line 348, in _handle_input
    output(self.prompt)
  File "/usr/local/lib/python3.8/site-packages/launcher/shell/shell.py", line 16, in output
    os.write(sys.stdout.fileno(), seq.encode())
```

**Comment by kilrau** [comment]
As discussed earlier this happens when printing "too much". I didn't see this in a while. Is the 100 lines max implemented? @reliveyy 

If so, we can close here.
