### ISSUE TITLE
Failed to launch environment

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#302]
Looks like the request to DockerHub timed out and caused the environment not to start. I double checked that I was connected to the internet.

Expected behaviour is to try again and display a nicer error message if the retry attempt fails.

```
🚀 Launching testnet environment
/home/ar/.xud-docker/testnet does not exist, would you like to
🌍 Checking for updates ...
Failed to check for image updates. Try again? [Y/n] Y
* Image exchangeunion/litecoind:0.17.1: missing
* Image exchangeunion/xud:latest: missing
* Image exchangeunion/geth:1.9.10: missing
* Image exchangeunion/raiden:latest: missing
* Image exchangeunion/lnd:0.8.2-beta: missing
* Image exchangeunion/bitcoind:0.19.0.1: missing
* Container testnet_bitcoind_1: missing
* Container testnet_litecoind_1: missing
* Container testnet_geth_1: missing
* Container testnet_lndbtc_1: missing
* Container testnet_lndltc_1: missing
* Container testnet_raiden_1: missing
* Container testnet_xud_1: missing
Pulling exchangeunion/litecoind:0.17.1
Pulling exchangeunion/xud:latest
Pulling exchangeunion/geth:1.9.10
Pulling exchangeunion/raiden:latest
Pulling exchangeunion/lnd:0.8.2-beta
Pulling exchangeunion/bitcoind:0.19.0.1
❌ Failed to launch testnet environment. For more details, see
```

xud-docker.log
```
2020-02-20 21:43:23.711 ERROR 1 --- [MainThread] launcher.Launcher: Failed to launch
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/images/create?tag=0.19.0.1&fromImage=exchangeunion%2Fbitcoind

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/launcher/launcher.py", line 651, in launch
    env.start()
  File "/usr/local/lib/python3.8/site-packages/launcher/launcher.py", line 626, in start
    self.check_updates()
  File "/usr/local/lib/python3.8/site-packages/launcher/launcher.py", line 515, in check_updates
    img = self._client.images.pull(image_name)
  File "/usr/local/lib/python3.8/site-packages/docker/models/images.py", line 444, in pull
    pull_log = self.client.api.pull(
  File "/usr/local/lib/python3.8/site-packages/docker/api/image.py", line 415, in pull
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/exchangeunion/bitcoind/manifests/0.19.0.1: Get https://auth.docker.io/token?scope=repository%3Aexchangeunion%2Fbitcoind%3Apull&service=registry.docker.io: net/http: TLS handshake timeout")
```

**Comment by reliveyy** [comment]
@erkarl I've encountered this "TLS handshake timeout" too. We could add a retry wrapper to provide a more user friendly experience.

**Comment by kilrau** [comment]
Closely related: https://github.com/ExchangeUnion/xud-docker/issues/272

**Comment by kilrau** [comment]
Since https://github.com/ExchangeUnion/xud-docker/issues/272 solved the situation for me, can you still reproduce this? @erkarl

**Comment by erkarl** [comment]
Haven't seen this error in a while. Let's close and reopen when it comes back.
