### ISSUE TITLE
Non-existing network dir causes crash

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#359]
**Describe the bug**
Specifying a <network> dir which doesn't exist, causes xud-docker to crash. If the specified directory is created manually (mkdir), things work as intended.

```
kilrau@K-Yoga:~/.xud-docker/mainnet$ xud --testnet-dir /home/kilrau/.xud-docker/testnet-light
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
Pulling image exchangeunion/utils:latest
🚀 Launching testnet environment
Warning: Using deprecated field "external". Please use "mode" instead.
Warning: Please use field "mode" to specify Infura usage.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/shell/history.py", line 21, in __init__
    with open(self._history_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/hostfs/home/kilrau/.xud-docker/testnet-light/history'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/__init__.py", line 131, in launch
    sh.set_network_dir(cfg.network_dir)  # will create shell history file in network_dir
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/shell/shell.py", line 517, in set_network_dir
    self.handler.set_network_dir(network_dir)
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/shell/shell.py", line 303, in set_network_dir
    self._history = History(self._cmd, get_hostfs_file(f"{network_dir}/history"))
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/shell/history.py", line 29, in __init__
    with open(self._history_file, 'w'):
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/hostfs/home/kilrau/.xud-docker/testnet-light/history'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/__main__.py", line 3, in <module>
    Launcher().launch()
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/__init__.py", line 161, in launch
    copyfile("/var/log/launcher.log", get_hostfs_file(cfg.logfile))
  File "/usr/local/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/hostfs/home/kilrau/.xud-docker/testnet-light/logs/testnet-2020-03-25-18-03-01.log'
```

**Comment by reliveyy** [comment]
Confirmed. It will be fixed soon.
