### ISSUE TITLE
Testnet/Mainnet environment fails to start

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#386]
**Describe the bug**
1. Testnet fails to start with:
```
xud@raspixud:~$ xud
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
Pulling image exchangeunion/utils:latest
🚀 Launching testnet environment
🌍 Checking for updates...
Failed to check for container updates.
- lndbtc: 'Image' object has no attribute 'digest'
- lndltc: 'Image' object has no attribute 'digest'
- xud: 'Image' object has no attribute 'digest'
- raiden: 'Image' object has no attribute 'digest'
Try again? [Y/n] ^C
```

Mainnet fails to start with:
```
xud@raspixud:~$ xud
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 3
Warning: Use local exchangeunion/utils:20.04.02 (newer than cloud exchangeunion/utils:20.04.02)
🚀 Launching mainnet environment
❌ Failed to launch mainnet environment. For more details, see /media/SSD/03-Mainnet/logs/mainnet-2020-04-09-11-22-48.log
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/config/config.py", line 797, in get_nodes_json
    r = urlopen(f"https://raw.githubusercontent.com/ExchangeUnion/xud-docker/{self.branch}/nodes.json")
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/__init__.py", line 137, in launch
    cfg.parse()
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/config/config.py", line 433, in parse
    node_json = self.get_nodes_json()
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/config/config.py", line 800, in get_nodes_json
    raise NodesJsonMissing()
launcher.config.config.NodesJsonMissing
```

**Comment by kilrau** [comment]
- on a `amd64` machine where I was running testnet yesterday, the environment came up successfully. If I had to guess, the "print image details" PR screwed up the update check somehow removing the image `digest`
- if I decline the update, the environment comes up:
```
Failed to check for container updates.
- lndbtc: 'Image' object has no attribute 'digest'
- raiden: 'Image' object has no attribute 'digest'
- xud: 'Image' object has no attribute 'digest'
- lndltc: 'Image' object has no attribute 'digest'
Try again? [Y/n] n

                           .___           __  .__   
          ___  _____ __  __| _/     _____/  |_|  |  
          \  \/  /  |  \/ __ |    _/ ___\   __\  |  
           >    <|  |  / /_/ |    \  \___|  | |  |__
          /__/\_ \____/\____ |     \___  >__| |____/
                \/          \/         \/           
--------------------------------------------------------------

testnet >
```
