### ISSUE TITLE
Cant deploy docker setup successfully on DigitalOcean instance after previous setup removing

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-docker#666]
Having another issue, I ended up setting a digital ocean environment for another xud, since starting 2 different xuds in local is a pain for my environment :/ But on my droplet here how it seems, I tried to remove entire .xud-docker folder and all containers and started over a few times no luck.

https://media.discordapp.net/attachments/589875048043642884/744835850738860042/unknown.png?width=1424&height=900

from xud docker logs;

```[xud-backup] Waiting for backup_dir value
17/08/2020 08:33:54.655 [LND-LTC] error: AssertionError [ERR_ASSERTION]: awaitWalletInit should not be called from a status besides Initialized or Unlocked
    at LndClient.<anonymous> (/app/dist/lndclient/LndClient.js:358:38)
    at Generator.next (<anonymous>)
    at /app/dist/lndclient/LndClient.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/dist/lndclient/LndClient.js:23:12)
    at LndClient.awaitWalletInit (/app/dist/lndclient/LndClient.js:337:42)
    at LndClient.<anonymous> (/app/dist/lndclient/LndClient.js:402:30)
    at Generator.next (<anonymous>)
    at /app/dist/lndclient/LndClient.js:27:71
    at new Promise (<anonymous>)
[11:34]```
also I don't see an issue on ltc container

```59466605f0231d973359
2020-08-17 08:34:02.105 [INF] LTCN: Verified 1 filter header in the last 1m0.31s (height 74476, 2020-08-17 08:34:01 +0000 UTC)
2020-08-17 08:34:27.103 [DBG] LTCN: Sending ping to 35.231.222.142:39555 (outbound)
2020-08-17 08:34:27.502 [DBG] LTCN: Received ping from 35.231.222.142:39555 (outbound)
2020-08-17 08:34:27.502 [DBG] LTCN: Sending pong to 35.231.222.142:39555 (outbound)
2020-08-17 08:34:27.531 [DBG] LTCN: Received pong from 35.231.222.142:39555 (outbound)```

https://we.tl/t-kOKDqfwcow



**_Task to me: retest it._**

Comment: ```I chose Ubuntu 20 LTS and installed docker via snap```

**Comment by raladev** [comment]
Closed, problem was in  host machine stats: 1GB RAM instead of 2 GB.
