### ISSUE TITLE
Stuck on interrupting syncing light clients

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#685]
```
Syncing light clients:
┌─────────┬─────────────────────────────────────────────────────┐
│ SERVICE │ STATUS                                              │
├─────────┼─────────────────────────────────────────────────────┤
│ lndbtc  │ Syncing 100.00% (645268/645267)                     │
├─────────┼─────────────────────────────────────────────────────┤
│ lndltc  │ Syncing 77.80% (1479000/1900802)                    │
└─────────┴─────────────────────────────────────────────────────┘
^C^C
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/local/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

**Comment by kilrau** [comment]
How it should be: it should allow to exit the environment with CTRL+C, not interrupt the sync, not `down` anything, just exit the shell. When entering the environment, same network again, it'll take you back where you left off.
