### ISSUE TITLE
Add "Image X not found" error message

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#700]
**Describe the bug**
Currently, whenever an image from the template file is not found on dockerhub, the environment throws:
```
❌ Error: Timeout error: Couldn't connect to Docker to check for updates. Please check your internet connection and https://status.docker.com/.. For more details, see /home/d/.xud-docker/mainnet/logs/mainnet.log
```

**Expected behavior**
❌ Error: Image connext:1.3.1 not found @ https://hub.docker.com/repository/docker/exchangeunion/connext/tags

**Comment by kilrau** [comment]
Mainnet logs clearly show which image was not found:
```
2020-08-31 13:26:33,959 ERROR 1 --- [EventLoop] launcher.shell.EventLoop: The loop exits unexpectedly
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/shell/shell.py", line 212, in run
    events = self.selector.select(timeout=1)
  File "/usr/local/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
OSError: [Errno 9] Bad file descriptor
2020-08-31 13:26:33,965 DEBUG 1 --- [EventLoop] launcher.shell.EventLoop: End
2020-08-31 13:38:42,690 INFO 1 --- [MainThread] launcher.Config: Parsed mainnet.conf: {'backup-dir': '/media/USB/xud-backup/03-Mainnet', 'bitcoind': {'mode': 'external', 'r>
2020-08-31 13:38:45,352 ERROR 1 --- [ThreadPoolExecutor-0_4] launcher.node.Image: Image not found on cloud: exchangeunion/arby:1.1.8 (retry in 10 seconds)
NoneType: None
2020-08-31 13:38:56,323 ERROR 1 --- [ThreadPoolExecutor-0_4] launcher.node.Image: Image not found on cloud: exchangeunion/arby:1.1.8 (retry in 10 seconds)
NoneType: None
2020-08-31 13:39:07,262 ERROR 1 --- [ThreadPoolExecutor-0_4] launcher.node.Image: Image not found on cloud: exchangeunion/arby:1.1.8 (retry in 10 seconds)
NoneType: None
2020-08-31 13:39:13,603 ERROR 1 --- [MainThread] launcher.utils: Task <Image name='exchangeunion/arby:1.1.8' use='exchangeunion/arby:1.1.8' pull=None> timeout
2020-08-31 13:39:17,273 DEBUG 1 --- [MainThread] launcher.shell.Shell: stop
2020-08-31 13:39:17,274 DEBUG 1 --- [InputHandler] launcher.shell.InputHandler: End
2020-08-31 13:39:17,967 DEBUG 1 --- [EventLoop] launcher.shell.EventLoop: End
2020-08-31 13:39:40,686 INFO 1 --- [MainThread] launcher.Config: Parsed mainnet.conf: {'backup-dir': '/media/USB/xud-backup/03-Mainnet', 'bitcoind': {'mode': 'external', 'r>
2020-08-31 13:39:40,675 DEBUG 1 --- [InputHandler] launcher.shell.InputHandler: Begin
2020-08-31 13:39:43,154 ERROR 1 --- [ThreadPoolExecutor-0_4] launcher.node.Image: Image not found on cloud: exchangeunion/arby:1.1.8 (retry in 10 seconds)
NoneType: None
2020-08-31 13:39:54,104 ERROR 1 --- [ThreadPoolExecutor-0_4] launcher.node.Image: Image not found on cloud: exchangeunion/arby:1.1.8 (retry in 10 seconds)
NoneType: None
2020-08-31 13:40:05,132 ERROR 1 --- [ThreadPoolExecutor-0_4] launcher.node.Image: Image not found on cloud: exchangeunion/arby:1.1.8 (retry in 10 seconds)
NoneType: None
2020-08-31 13:40:11,946 ERROR 1 --- [MainThread] launcher.utils: Task <Image name='exchangeunion/arby:1.1.8' use='exchangeunion/arby:1.1.8' pull=None> timeout
2020-08-31 13:40:15,143 DEBUG 1 --- [MainThread] launcher.shell.Shell: stop
2020-08-31 13:40:15,144 DEBUG 1 --- [InputHandler] launcher.shell.InputHandler: End
2020-08-31 13:40:15,776 DEBUG 1 --- [EventLoop] launcher.shell.EventLoop: End
```
