### ISSUE TITLE
xud.sh not working on osx

### ISSUE THREAD

**Issue by rsercano** [ExchangeUnion/xud-docker#789]
**Docker info:**

```
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 34
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.39-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.941GiB
 Name: docker-desktop
 ID: YTTZ:2GLG:OT47:2PIA:JP6J:2MJK:BBWF:TOLR:LSUW:NDWG:WTN6:OM7A
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 47
  System Time: 2020-11-18T19:28:43.636762637Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Without grpc fuse:**

![image](https://user-images.githubusercontent.com/3640368/99659403-e2392900-2a71-11eb-82f5-09f16e810775.png)

**With grpc fuse:**

```
➜  ~ bash xud.sh 
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 1
🚀 Launching simnet environment
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/__init__.py", line 273, in launch
    config = Config(ConfigLoader())
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/config/config.py", line 37, in __init__
    self.home_dir = self.loader.ensure_home_dir(os.environ["HOST_HOME"])
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/config/loader.py", line 47, in ensure_home_dir
    os.mkdir(hostfs_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/hostfs/Users/sercanozdemir/.xud-docker'
```

**Comment by reliveyy** [comment]
Related to https://github.com/docker/docker-py/issues/2696

**Comment by kilrau** [comment]
Made this a P3 "watch only" issue since we are simply waiting for a fix on docker side observing above linked issue.

**Comment by kilrau** [comment]
Still unfixed: https://github.com/docker/docker-py/issues/2696#issuecomment-731178881

**Comment by kilrau** [comment]
Since this is still not fixed by docker, how about we also use the workaround linked in the issue (https://github.com/getsentry/sentry/pull/22250/files#diff-1125ff5a13bc41637ad61c8bd8edbc84dc7a8436b8a6ad3a8b95f16d65156913R12)

**Comment by kilrau** [comment]
Can you guys run edge (2.5.2) to see if it [fixes this issue](https://github.com/docker/docker-py/issues/2696#issuecomment-736660016)? @peartobear @reliveyy

**Comment by kilrau** [comment]
https://github.com/docker/docker-py/issues/2696#issuecomment-736660016

**Comment by peartobear** [comment]
It's not working for me right now. Cli exits after attempting to pull images

```
Ankurs-MacBook-Air:~ ankurkumar$ bash xud.sh
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
🚀 Launching testnet environment
🌍 Checking for updates...
- Image exchangeunion/proxy:latest: pull
- Image exchangeunion/boltz:latest: pull
- Image exchangeunion/lndltc:latest: pull
- Image exchangeunion/lndbtc:latest: pull
- Image exchangeunion/xud:latest: pull
- Image exchangeunion/connext:latest: pull
Ankurs-MacBook-Air:~ ankurkumar$ 
```

**Comment by kilrau** [comment]
Thanks! cc @reliveyy
